server:
  port: ${PORT:8080}

logging:
  level:
    root: warn
    com.jcompile.reidlo: debug

spring:
  messages:
    basename: i18n/exception
    encoding: UTF-8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
