spring:
  config:
    activate:
      on-profile: local
  url:
    base: http://localhost:8080

  messages:
    basename: i18n/exception
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hackathon2022-tot-db.cxogw3mpnveh.ap-northeast-2.rds.amazonaws.com/totDB?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: totAdmin
    password: III!2022

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql