server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  url:
    base: http://localhost:8080

  messages:
    basename: i18n/exception
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jcompile?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: spring5
    password: spring5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql