server:
  port: ${PORT:8080}

logging:
  level:
    root: warn
    com.jcompile.reidlo: debug

spring:
  url:
    base: http://localhost:8080

  messages:
    basename: i18n/exception
    encoding: UTF-8
